version: "latest"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - accents-game

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - accents-game

networks:
  accents-game:
    driver: bridge