version: "latest"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - network

  frontend:
    env_file:
      - path: ./env.local
        required: true
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - network

networks:
  network:
    driver: bridge
